# Generated by Django 3.2.9 on 2022-10-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agentname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.IntegerField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=2000, null=True)),
                ('lastname', models.CharField(blank=True, max_length=2000, null=True)),
                ('email', models.CharField(blank=True, max_length=2000, null=True)),
                ('phone', models.CharField(blank=True, max_length=2000, null=True)),
                ('pollingunit_uniqueid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncedLgaResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(blank=True, null=True)),
                ('lga_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('party_abbreviation', models.CharField(blank=True, max_length=2000, null=True)),
                ('party_score', models.IntegerField(blank=True, null=True)),
                ('entered_by_user', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_entered', models.DateField(blank=True, null=True)),
                ('user_ip_address', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncedPuResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(blank=True, null=True)),
                ('polling_unit_uniqueid', models.IntegerField(blank=True, null=True)),
                ('party_abbreviation', models.CharField(blank=True, max_length=2000, null=True)),
                ('party_score', models.IntegerField(blank=True, null=True)),
                ('entered_by_user', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_entered', models.CharField(blank=True, max_length=2000, null=True)),
                ('user_ip_address', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncedStateResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(blank=True, null=True)),
                ('state_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('party_abbreviation', models.CharField(blank=True, max_length=2000, null=True)),
                ('party_score', models.IntegerField(blank=True, null=True)),
                ('entered_by_user', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_entered', models.CharField(blank=True, max_length=2000, null=True)),
                ('user_ip_address', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncedWardResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(blank=True, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('party_abbreviation', models.CharField(blank=True, max_length=2000, null=True)),
                ('party_score', models.IntegerField(blank=True, null=True)),
                ('entered_by_user', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_entered', models.CharField(blank=True, max_length=2000, null=True)),
                ('user_ip_address', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.IntegerField(blank=True, null=True)),
                ('lga_id', models.IntegerField(blank=True, null=True)),
                ('lga_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('lga_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('entered_by_user', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_entered', models.CharField(blank=True, max_length=2000, null=True)),
                ('user_ip_address', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('partyid', models.IntegerField(blank=True, null=True)),
                ('partyname', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.IntegerField(blank=True, null=True)),
                ('polling_unit_id', models.IntegerField(blank=True, null=True)),
                ('ward_id', models.IntegerField(blank=True, null=True)),
                ('lga_id', models.IntegerField(blank=True, null=True)),
                ('uniquewardid', models.IntegerField(blank=True, null=True)),
                ('polling_unit_number', models.IntegerField(blank=True, null=True)),
                ('polling_unit_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('polling_unit_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('lat', models.CharField(blank=True, max_length=2000, null=True)),
                ('long', models.CharField(blank=True, max_length=2000, null=True)),
                ('entered_by_user', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_entered', models.DateField(blank=True, null=True)),
                ('user_ip_address', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('state_name', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.IntegerField(blank=True, null=True)),
                ('ward_id', models.IntegerField(blank=True, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('lga_id', models.IntegerField(blank=True, null=True)),
                ('ward_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('entered_by_user', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_entered', models.CharField(blank=True, max_length=2000, null=True)),
                ('user_ip_address', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
