# Generated by Django 3.2.9 on 2022-10-31 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingunit',
            options={'managed': False},
        ),
    ]
