# Generated by Django 4.1.1 on 2022-11-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221031_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcedpuresults',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lga',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'managed': False},
        ),
    ]
