# Generated by Django 3.2.9 on 2022-11-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_announcedpuresults_options_alter_lga_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcedpuresults',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='lga',
            table='lga',
        ),
        migrations.AlterModelTable(
            name='party',
            table='party',
        ),
        migrations.AlterModelTable(
            name='ward',
            table='ward',
        ),
    ]
