# Generated by Django 3.2.9 on 2022-11-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221104_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcedpuresults',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lga',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pollingunit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'managed': True},
        ),
    ]
