# Generated by Django 3.2.9 on 2022-11-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221104_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcedpuresults',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lga',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pollingunit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='id',
        ),
        migrations.AlterField(
            model_name='announcedpuresults',
            name='result_id',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lga',
            name='lga_id',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='uniqueid',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_id',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='announcedpuresults',
            table='announced_pu_results',
        ),
    ]
